version: "3.8"

services:
  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    ports:
      - "7474:7474"   # Interface web
      - "7687:7687"   # Bolt (connexion Python)
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
      - ./neo4j_import:/var/lib/neo4j/import
      - ./neo4j_plugins:/plugins
